name: ChatBot App CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set OPENAI_API_KEY environment variable
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

      # Ensure workflow stops on test failure
      continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Docker
      run: |
        docker build -t chatbot-app -f docker/Dockerfile .
        docker run -p 5000:5000 --env-file app/.env --name chatbot-app chatbot-app